#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_all(KC_LCTL, TG(1), KC_A, KC_I, KC_B, KC_J, KC_C, KC_K, KC_D, KC_9, KC_E, KC_L, KC_F, KC_M, KC_G, KC_N, KC_H, KC_O),
	[1] = LAYOUT_all(KC_NO, KC_TRNS, KC_1, KC_0, KC_2, KC_9, KC_3, KC_8, KC_4, KC_7, KC_5, KC_6, KC_6, KC_5, KC_7, KC_4, KC_8, KC_3)
};

